config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new'
    post 'sign_up', to: 'devise/registrations#create'
    get 'sign_in', to: 'devise/sessions#new'
    post 'sign_in', to: 'devise/sessions#create'
    get 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    delete 'sign_out', to: 'devise/sessions#destroy'
    get 'profile/edit', to: 'devise/registrations#edit'
  
  end
  resources :articles do
    resources :comments, only: [:create]
  end
  
  get 'user/:id', to: 'users#show'
  get 'users', to: 'users#index'
  resources :user
  get 'new-article', to: 'articles#new'
  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'
  root 'articles#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_one :content, class_name: 'ActionText::RichText', as: :record
    has_rich_text :content
    has_one_attached :image
    has_many :comments
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /articles or /articles.json
  def index
    @categories = Category.all
    @q = Article.ransack(params[:q])
    
    cat = params[:cat]
    if !cat.nil?
      @articles = Article.where(:category_id => cat).paginate(page: params[:page], per_page: 6).order(id: :desc)
    else
      @articles = @q.result.paginate(page: params[:page], per_page: 6).order(id: :desc)
    end
  end

  # GET /articles/1 or /articles/1.json
  def show
    @q = Article.ransack(params[:q])
    @categories = Category.all

  end

  # GET /articles/new
  def new
    @article = Article.new
    @categories = Category.all
    
  end

  # GET /articles/1/edit
  def edit
    @categories = Category.all

  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    @categories = Category.all.map {|c| [c.name, c.id]}


    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :image, :category_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="col-xl-8 col-lg-8 col-md-12 col-sm-12">
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :image, "Choose cover image" %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-primary" %>
  </div>

  <%= link_to 'Back', articles_path %>
</div>


<div class="col-xl-4 col-lg-4 col-md-12 col-sm-12">

          <div class="widget categories">
            <header>
                <h3 class="h6">Post Cover image</h3>
              </header>
              <%= image_tag(@article.image, width: "100%") if @article.image.attached? %>
          </div>

          <div class="widget categories">
              <header>
                <h3 class="h6">Categories</h3>
              </header>
              <%= form.select :category_id, Category.all.map {|c| [c.name, c.id]} %> <br>
          </div>

          <div class="widget categories">
              <header>
                <h3 class="h6">Article Status</h3>
              </header>
              
              <select class="custom-select" id="inputGroupSelect01">
                  <option selected>Save to Draft</option>
                  <option class="">Publish</option>
              </select>
          </div>

<!-- tags section -->
          <div class="widget tags">       
            <header>
              <h3 class="h6">Tags</h3>
            </header>
            <input type="text" class="form-control mb-2" placeholder="new tags?" aria-label="Recipient's username" aria-describedby="basic-addon2">
  
            <ul class="list-inline">
              <li class="list-inline-item"><a href="#" class="tag">#Business</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Technology</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Fashion</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Sports</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Economy</a></li>
            </ul>
          </div>
            
        </div>


<% end %>

app/views/articles/edit.html.erb
<div class="container mt-5 mb-5">
    <div class="row">



        <%= render 'form', article: @article %>

        

        </div>

         

<!-- tags section -->
          
            
          </div>
        </div>

        



    </div>
</div>

app/views/articles/index.html.erb
<div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8"> 
          <div class="container">
            <div class="row">
              <!-- post -->
               <% @articles.each do |article| %>
              <div class="post col-xl-6 ">
                <div class="post-thumbnail"><%= link_to article do %>
                <%= image_tag(article.image, class: "img-fluid post-thumbnail rounded-top" ) if article.image.attached? %>
                <% end %> </div>
                <div class="post-details border p-2 rounded-bottom">
                  <div class="post-meta d-flex justify-content-between">
                    <div class="date meta-last"> <%= article.created_at.strftime("%d %b, | %Y") %></div>
                    <div class="category"><%= link_to article.category.name, articles_path(:cat => article.category.id) if article.category.name.present? %></div>
                  </div><%= link_to article do %>
                    <h3 class="h4"><%=  article.title %></h3><% end %>
                  <p class="text-muted"><%= article.content.to_plain_text.truncate(100) %></p>
                  <footer class="post-footer d-flex align-items-center"><div class="author d-flex align-items-center flex-wrap">
                     <%= link_to article.user do %> <%= image_tag(article.user.avatar, class: "avatar img-fluid") %><% end %>
                    <%= link_to article.user do %>  <div class="title"><span><%= article.user.first_name + " " + article.user.last_name %></span></div> <% end %>
                    <div class="date"><i class="bi bi-clock"></i> <%= article.created_at.strftime("%d %b, %Y") %></div>
                    <div class="comments meta-last"><i class="bi bi-chat-left-dots"></i><%= article.comments.count %></div>
                  </footer>
                </div>
              </div>
              <% end %> 

              <!-- post-end -->
              
            </div>
            <!-- Pagination -->
            <nav aria-label="  Page navigation example">
              <ul class=" digg_pagination pagination pagination-template d-flex justify-content-center">
                
                <%= will_paginate @article, :container => false %>
                
              </ul>
            </nav>
          </div>
        </main>
        <aside class="col-lg-4">
          <!-- Widget [Search Bar Widget]-->
          <%= render "shared/search" %>

          <%= render "shared/ads" %>
          <!-- Widget [Latest Posts Widget]        -->
          <%= render "shared/latest" %>
          <!-- Widget [Categories Widget]-->
          <%= render "shared/ads" %>
          <!-- Widget [Categories Widget]-->
          <%= render "shared/categ" %>
          <!-- Widget [Tags Cloud Widget]-->
          <%= render "shared/ads" %>
        </aside>
      </div>
    </div>

app/views/articles/new.html.erb
<div class="container mt-5 mb-5">
    <div class="row">

        <%= render 'form', article: @article %>

      </div>

    </div>
</div>

app/views/articles/show.html.erb
     <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="post blog-post col-lg-8"> 
          <div class="container">
            <div class="post-single">
            <% if @article.user == current_user %>
            <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-secondary mb-3 btn-sm" %> |
            <%= link_to 'Back', articles_path, class: "btn btn-outline-secondary mb-3 btn-sm" %>
            <% end %>
              <div class="post-thumbnail"><%= image_tag(@article.image) if @article.image.attached? %></div>
              <div class="post-details">
                <div class="post-meta d-flex justify-content-between">
                  <div class="category"><%= link_to @article.category.name, articles_path(:cat => @article.category.id) if @article.category.name.present? %></div>
                </div>
                <h2><%= @article.title %><a href="#"><i data-placement="right" title="Bookmark this Article!" class="bi bi-bookmarks"></i></a></h2>
                <div class="post-footer d-flex align-items-center flex-column flex-sm-row"><a class="author d-flex align-items-center flex-wrap">
                    <%= link_to @article.user do %><div class="avatar"><%= image_tag(@article.user.avatar, class: "avatar img-fluid") %></div><% end %>
                    <%= link_to @article.user do %><div class="title"><span><%= @article.user.first_name + " " + @article.user.last_name %></span></div></a><% end %>
                  <div class="d-flex align-items-center flex-wrap">       
                    <div class="date"><i class="bi bi-clock"></i> <%= @article.created_at.strftime("%d %b, %Y  %H:%M") %></div>
                    <div class="views"><i class="bi bi-eye"></i> 500</div>
                    <div class="comments meta-last"><i class="bi bi-chat-left-dots"></i><%= @article.comments.count %></div>
                  </div>
                </div>
                <div class="post-body">
                  <p><%= @article.content %></p>
                  
                </div>
                <div class="post-tags"><a href="#" class="tag">#Business</a><a href="#" class="tag">#Tricks</a><a href="#" class="tag">#Financial</a><a href="#" class="tag">#Economy</a></div>
                
                 <div class="post-comments">
                  <header>
                    <h3 class="h6">Post Comments<span class="no-of-comments">(<%= @article.comments.count %>)</span></h3>
                  </header>
                     <%= render @article.comments.where(parent_id: nil ).includes(:user).order(id: :desc) %>
                  </div>
                
                <div class="add-comment">
                    <header>
                    <h3 class="h6">Leave a reply</h3>
                    </header>
                <%= render "comments/form", locals: {article: @article, parent: nil } %>
                </div>
              </div>
            </div>
          </div>
        </main>


        
        <aside class="col-lg-4">
          <!-- Widget [Search Bar Widget]-->
          <%= render "shared/search" %>

          <%= render "shared/ads" %>

          <!-- Widget [Latest Posts Widget]        -->
          <%= render "shared/latest" %>

          <%= render "shared/ads" %>

          <!-- Widget [Categories Widget]-->
          <%= render "shared/categ" %>
          <!-- Widget [Tags Cloud Widget]-->
          <%= render "shared/ads" %>
        </aside>
      </div>
    </div>