config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new'
    post 'sign_up', to: 'devise/registrations#create'
    get 'sign_in', to: 'devise/sessions#new'
    post 'sign_in', to: 'devise/sessions#create'
    get 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    delete 'sign_out', to: 'devise/sessions#destroy'
    get 'profile/edit', to: 'devise/registrations#edit'
  
  end
  resources :articles do
    resources :comments, only: [:create]
  end
  
  get 'user/:id', to: 'users#show'
  get 'users', to: 'users#index'
  resources :user
  get 'new-article', to: 'articles#new'
  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'
  root 'articles#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_ads.html.erb
<div class="widget tags">       
<header>
    <small class="">Advertisement</small>
</header>
</div>

app/views/shared/_categ.html.erb
<div class="widget categories">
    <header>
        <h3 class="h6">Categories</h3>
    </header>
    <% @categories.each do | category | %>
    <div class="item d-flex justify-content-between"><%= link_to category.name, articles_path(:cat => category.id) %><span><%= category.articles.count %></span></div>
    <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="main-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="logo">
              <h6 class="text-white">Simple-Blog</h6>
            </div>
            <div class="contact-details">
              <p>53 Broadway, Broklyn, NY 11249</p>
              <p>Phone: (020) 123 456 789</p>
              <p>Email: <a href="mailto:info@company.com">Info@Company.com</a></p>
              <ul class="social-menu">
                <li class="list-inline-item"><a href="#"><i class="bi bi-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="bi bi-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="bi bi-instagram"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="bi bi-behance"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="bi bi-pinterest"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="menus d-flex">
              <ul class="list-unstyled">
                <li> <a href="#">My Account</a></li>
                <li> <a href="#">Add Listing</a></li>
                <li> <a href="#">Pricing</a></li>
                <li> <a href="#">Privacy &amp; Policy</a></li>
              </ul>
              <ul class="list-unstyled">
                <li> <a href="#">Our Partners</a></li>
                <li> <a href="#">FAQ</a></li>
                <li> <a href="#">How It Works</a></li>
                <li> <a href="#">Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="latest-posts"><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="https://images.unsplash.com/photo-1609929986803-c38576e2b091?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Hotels for all budgets</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="https://images.unsplash.com/photo-1609929986803-c38576e2b091?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Great street atrs in London</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="https://images.unsplash.com/photo-1609929986803-c38576e2b091?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Best coffee shops in Sydney</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a></div>
          </div>
        </div>
      </div>
      <div class="copyrights">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <p>&copy; 2017. All rights reserved. Your great site.</p>
            </div>
            <div class="col-md-6 text-right">
              <p>Template By <a href="https://bootstrapious.com/p/bootstrap-carousel" class="text-white">Bootstrapious</a>
                <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>

app/views/shared/_latest.html.erb
<div class="widget latest-posts">
    <header>
        <h3 class="h6">Latest Posts</h3>
    </header>
    <div class="blog-posts">
        <% Article.all.order("created_at Desc").limit(5).each do |article| %>
        <div class="item d-flex align-items-center">

    <%= link_to article do %><div class="image"><%= image_tag(article.image, width: "60", height: "55", style: "border-radius:5px;" ) if article.image.attached? %></div><% end %>
     <%= link_to article do %><div class="title"><strong><%= article.title %> </strong> <% end %>
            <div class="d-flex align-items-center">
                <div class="views"><i class="bi bi-eye"></i> 500</div>
                <div class="comments"><i class="bi bi-chat-left-dots"></i><%= article.comments.count %></div>
            </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/shared/_nav.html.erb
    <header class="header">
      <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg">
        <% if user_signed_in? %>
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><a href="/" class="navbar-brand"><h4>Simple-Blog</h4></a>
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
            
          </div>
          <!-- Navbar Menu -->
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <form class="form-inline my-2 my-md-0">
              <h4>Rolling out updates</h4>
              </form>
            </ul>
          </div>
            
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
         
              <!--notification dropdown-->
              <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" data-toggle="tooltip" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="bi bi-bell h5"></i></a>
                <div class="dropdown-menu dropdown-menu-right">
                  <a class="dropdown-item" href="#">Nothing Here</a>
                  
                </div>
              </li>
              <!--account dropdown-->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <%= image_tag(current_user.avatar, width: "30", height: "30", style: "border-radius: 50%") %></a>
                <div class="dropdown-menu dropdown-menu-lg-right">
                  <a class="dropdown-item" href="#"><%= current_user.username %> <br> <span><%= current_user.email %></span></a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#"><i class="bi bi-bar-chart"></i> Analytics</a>
                  <a class="dropdown-item" href="#"><i class="bi bi-bell"></i> Notifications <span class="badge badge-secondary">4</span></a>
                  <a class="dropdown-item" href="/new-article"><i class="bi bi-pencil-square"></i> New Article</a>
                  <a class="dropdown-item" href="/articles"><i class="bi bi-journal-richtext"></i> Articles</a>
                  <%= link_to user_path(current_user) do  %>
                  <span class="dropdown-item"><i class="bi bi-person"></i> Profile</span>
                  <% end%>
                  <a class="dropdown-item" href="#"><i class="bi bi-bookmark-heart"></i> Bookmarks</a>
                  <a class="dropdown-item text-success" href="#"><i class="bi bi-person-check"></i> Become a Member</a>
                  <a class="dropdown-item" href="/articles" target="_blank"><i class="bi bi-life-preserver"></i> Help /Support</a>
                  <a class="dropdown-item" href="/profile/edit"><i class="bi bi-gear-wide-connected"></i> User Settings</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item text-danger" href="/sign_out"><i class="bi bi-box-arrow-right"></i> Sign-Out</a>
                </div>
              </li>
              
            </ul>
          </div>

        </div>
        <% else %>

        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><a href="/" class="navbar-brand"><h4>Simple-Blog</h4></a>
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
            
          </div>
          <!-- Navbar Menu -->
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a href="/" class="nav-link ">Articles</a></li>
              <li class="nav-item"><a href="/about" class="nav-link ">About</a></li>
              <li class="nav-item"><a href="/contact" class="nav-link ">Contact</a></li>
            </ul>
          </div>
            
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class=""><a href="/sign_in" class="btn btn-outline-secondary btn-sm brads ">Sign In</a></li>
              <li class=""><a href="/sign_up" class="btn btn-secondary btn-sm brads ml-2">Sign Up</a></li> 
            </ul>
          </div>

        </div>
        <% end %>

      </nav>
    </header>

app/views/shared/_notice.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

app/views/shared/_search.html.erb
<div class="widget search">
<header>
    <h3 class="h6">Search the blog</h3>
</header>
<%= search_form_for @q do |f| %>
    <div class="form-group">
      <%= f.search_field :title_or_content_body_cont, placeholder: "Search articles by title" %>
    <button type="submit" class="submit"><i class="bi bi-search"></i></button>
    </div>
<% end %>
</div>